.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2013 Damien Cassou <damien.cassou@gmail.com>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH PHARO 1 "September 2013" "PHARO" "Pharo" "User Commands"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
pharo \- A clean and innovative Smalltalk-inspired environment.
.SH SYNOPSIS
.B pharo
.SH BUGS
No known bugs (what did you expect?).
.SH AUTHOR
Damien Cassou (damien.cassou@gmail.com)
